package syslog_prase

import "github.com/miekg/dns"

var StringNumberToType = reverseInt16(TypeToStringNumber)

func reverseInt16(m map[uint16]string) map[string]uint16 {
	n := make(map[string]uint16, len(m))
	for u, s := range m {
		n[s] = u
	}
	return n
}

// TypeToString is a map of strings for each RR type.
var TypeToStringNumber = map[uint16]string{
	//dns.TypeNone:       "0",
	dns.TypeA:          "1",
	dns.TypeNS:         "2",
	dns.TypeMD:         "3",
	dns.TypeMF:         "4",
	dns.TypeCNAME:      "5",
	dns.TypeSOA:        "6",
	dns.TypeMB:         "7",
	dns.TypeMG:         "8",
	dns.TypeMR:         "9",
	dns.TypeNULL:       "10",
	dns.TypePTR:        "12",
	dns.TypeHINFO:      "13",
	dns.TypeMINFO:      "14",
	dns.TypeMX:         "15",
	dns.TypeTXT:        "16",
	dns.TypeRP:         "17",
	dns.TypeAFSDB:      "18",
	dns.TypeX25:        "19",
	dns.TypeISDN:       "20",
	dns.TypeRT:         "21",
	dns.TypeNSAPPTR:    "23",
	dns.TypeSIG:        "24",
	dns.TypeKEY:        "25",
	dns.TypePX:         "26",
	dns.TypeGPOS:       "27",
	dns.TypeAAAA:       "28",
	dns.TypeLOC:        "29",
	dns.TypeNXT:        "30",
	dns.TypeEID:        "31",
	dns.TypeNIMLOC:     "32",
	dns.TypeSRV:        "33",
	dns.TypeATMA:       "34",
	dns.TypeNAPTR:      "35",
	dns.TypeKX:         "36",
	dns.TypeCERT:       "37",
	dns.TypeDNAME:      "39",
	dns.TypeOPT:        "41",
	dns.TypeAPL:        "42",
	dns.TypeDS:         "43",
	dns.TypeSSHFP:      "44",
	dns.TypeRRSIG:      "46",
	dns.TypeNSEC:       "47",
	dns.TypeDNSKEY:     "48",
	dns.TypeDHCID:      "49",
	dns.TypeNSEC3:      "50",
	dns.TypeNSEC3PARAM: "51",
	dns.TypeTLSA:       "52",
	dns.TypeSMIMEA:     "53",
	dns.TypeHIP:        "55",
	dns.TypeNINFO:      "56",
	dns.TypeRKEY:       "57",
	dns.TypeTALINK:     "58",
	dns.TypeCDS:        "59",
	dns.TypeCDNSKEY:    "60",
	dns.TypeOPENPGPKEY: "61",
	dns.TypeCSYNC:      "62",
	dns.TypeSVCB:       "64",
	dns.TypeHTTPS:      "65",
	dns.TypeSPF:        "99",
	dns.TypeUINFO:      "100",
	dns.TypeUID:        "101",
	dns.TypeGID:        "102",
	dns.TypeUNSPEC:     "103",
	dns.TypeNID:        "104",
	dns.TypeL32:        "105",
	dns.TypeL64:        "106",
	dns.TypeLP:         "107",
	dns.TypeEUI48:      "108",
	dns.TypeEUI64:      "109",
	dns.TypeURI:        "256",
	dns.TypeCAA:        "257",
	dns.TypeAVC:        "258",
	dns.TypeTKEY:       "249",
	dns.TypeTSIG:       "250",
	dns.TypeIXFR:       "251",
	dns.TypeAXFR:       "252",
	dns.TypeMAILB:      "253",
	dns.TypeMAILA:      "254",
	dns.TypeANY:        "255",
	dns.TypeTA:         "32768",
	dns.TypeDLV:        "32769",
	dns.TypeReserved:   "65535",
}

var StringTypeNumberToType = reverseInt16(TypeToStringTypeNumber)

// TypeToStringTypeNumber is a map of strings for each RR type.
var TypeToStringTypeNumber = map[uint16]string{
	//dns.TypeNone:       "0",
	dns.TypeA:          "TYPE1",
	dns.TypeNS:         "TYPE2",
	dns.TypeMD:         "TYPE3",
	dns.TypeMF:         "TYPE4",
	dns.TypeCNAME:      "TYPE5",
	dns.TypeSOA:        "TYPE6",
	dns.TypeMB:         "TYPE7",
	dns.TypeMG:         "TYPE8",
	dns.TypeMR:         "TYPE9",
	dns.TypeNULL:       "TYPE10",
	dns.TypePTR:        "TYPE12",
	dns.TypeHINFO:      "TYPE13",
	dns.TypeMINFO:      "TYPE14",
	dns.TypeMX:         "TYPE15",
	dns.TypeTXT:        "TYPE16",
	dns.TypeRP:         "TYPE17",
	dns.TypeAFSDB:      "TYPE18",
	dns.TypeX25:        "TYPE19",
	dns.TypeISDN:       "TYPE20",
	dns.TypeRT:         "TYPE21",
	dns.TypeNSAPPTR:    "TYPE23",
	dns.TypeSIG:        "TYPE24",
	dns.TypeKEY:        "TYPE25",
	dns.TypePX:         "TYPE26",
	dns.TypeGPOS:       "TYPE27",
	dns.TypeAAAA:       "TYPE28",
	dns.TypeLOC:        "TYPE29",
	dns.TypeNXT:        "TYPE30",
	dns.TypeEID:        "TYPE31",
	dns.TypeNIMLOC:     "TYPE32",
	dns.TypeSRV:        "TYPE33",
	dns.TypeATMA:       "TYPE34",
	dns.TypeNAPTR:      "TYPE35",
	dns.TypeKX:         "TYPE36",
	dns.TypeCERT:       "TYPE37",
	dns.TypeDNAME:      "TYPE39",
	dns.TypeOPT:        "TYPE41",
	dns.TypeAPL:        "TYPE42",
	dns.TypeDS:         "TYPE43",
	dns.TypeSSHFP:      "TYPE44",
	dns.TypeRRSIG:      "TYPE46",
	dns.TypeNSEC:       "TYPE47",
	dns.TypeDNSKEY:     "TYPE48",
	dns.TypeDHCID:      "TYPE49",
	dns.TypeNSEC3:      "TYPE50",
	dns.TypeNSEC3PARAM: "TYPE51",
	dns.TypeTLSA:       "TYPE52",
	dns.TypeSMIMEA:     "TYPE53",
	dns.TypeHIP:        "TYPE55",
	dns.TypeNINFO:      "TYPE56",
	dns.TypeRKEY:       "TYPE57",
	dns.TypeTALINK:     "TYPE58",
	dns.TypeCDS:        "TYPE59",
	dns.TypeCDNSKEY:    "TYPE60",
	dns.TypeOPENPGPKEY: "TYPE61",
	dns.TypeCSYNC:      "TYPE62",
	dns.TypeSVCB:       "TYPE64",
	dns.TypeHTTPS:      "TYPE65",
	dns.TypeSPF:        "TYPE99",
	dns.TypeUINFO:      "TYPE100",
	dns.TypeUID:        "TYPE101",
	dns.TypeGID:        "TYPE102",
	dns.TypeUNSPEC:     "TYPE103",
	dns.TypeNID:        "TYPE104",
	dns.TypeL32:        "TYPE105",
	dns.TypeL64:        "TYPE106",
	dns.TypeLP:         "TYPE107",
	dns.TypeEUI48:      "TYPE108",
	dns.TypeEUI64:      "TYPE109",
	dns.TypeURI:        "TYPE256",
	dns.TypeCAA:        "TYPE257",
	dns.TypeAVC:        "TYPE258",
	dns.TypeTKEY:       "TYPE249",
	dns.TypeTSIG:       "TYPE250",
	dns.TypeIXFR:       "TYPE251",
	dns.TypeAXFR:       "TYPE252",
	dns.TypeMAILB:      "TYPE253",
	dns.TypeMAILA:      "TYPE254",
	dns.TypeANY:        "TYPE255",
	dns.TypeTA:         "TYPE32768",
	dns.TypeDLV:        "TYPE32769",
	dns.TypeReserved:   "TYPE65535",
}
